#!/bin/sh

mkdir config
mkdir -p data
mkdir graph
mkdir lib
mkdir -p out/img
mkdir proppr

tar xf data.tar.gz

git submodule update

cd lib/junto
bin/build update compile
cd ../..

cd lib/ProPPR
ant clean build
cd ../..
